import {
  NARRATIVE_AUTO_CHECK_IDS,
  type NarrativeAutoCheckEvidenceId,
  type NarrativeAutoCheckId,
  type NarrativeAutoCheckReportInput,
} from "../../src/contracts";

const CHECK_EVIDENCE = {
  "source-contracts": [],
  "story-check": ["story-check"],
  "sealed-narration": ["sealed-manifest", "complete-wav"],
  "semantic-timing": ["semantic-timing"],
  "project-registry": ["project-registry"],
  "narrative-baseline": [],
  "m3-evidence": ["m3-receipt"],
} as const satisfies Record<
  NarrativeAutoCheckId,
  readonly NarrativeAutoCheckEvidenceId[]
>;

type FailureReason = NarrativeAutoCheckReportInput["checks"][number]["failureReasons"][number];

const SAFE_MESSAGES = {
  missing: "Required narrative artifact is missing.",
  malformed: "Required narrative artifact is malformed.",
  stale: "Required narrative artifact is stale.",
  "checksum-mismatch": "Narrative artifact checksum does not match.",
  "identity-mismatch": "Narrative artifact identity does not match.",
  "registry-drift": "ProjectRegistry generated bytes are stale.",
  "media-invalid": "M3 media evidence is invalid.",
  unexpected: "Unexpected mechanical validation failure.",
} as const satisfies Record<FailureReason["code"], string>;

export const mapNarrativeCheckFailure = (
  checkId: NarrativeAutoCheckId,
  error: unknown,
): FailureReason => {
  const raw = error instanceof Error ? error.message.toLowerCase() : "";
  let code: FailureReason["code"] = "unexpected";
  if (checkId === "project-registry" && raw.includes("registry drift")) {
    code = "registry-drift";
  } else if (
    checkId === "m3-evidence" &&
    /ffmpeg|ffprobe|png|alpha|codec|media|render|evidence artifact/.test(raw)
  ) {
    code = "media-invalid";
  } else if (/missing|unreadable|enoent|not found|unknown project/.test(raw)) {
    code = "missing";
  } else if (/malformed|json|zod|unrecognized|invalid/.test(raw)) {
    code = "malformed";
  } else if (raw.includes("checksum")) {
    code = "checksum-mismatch";
  } else if (checkId === "project-registry" && raw.includes("drift")) {
    code = "registry-drift";
  } else if (/does not match|mismatch|differ/.test(raw)) {
    code = "identity-mismatch";
  } else if (/stale|drift/.test(raw)) {
    code = "stale";
  }
  return { code, message: SAFE_MESSAGES[code] };
};

export const createNarrativeCheckItem = ({
  checkId,
  status,
  error,
}: {
  readonly checkId: NarrativeAutoCheckId;
  readonly status: "pass" | "fail";
  readonly error?: unknown;
}): NarrativeAutoCheckReportInput["checks"][number] => ({
  checkId,
  status,
  evidenceIds: CHECK_EVIDENCE[checkId],
  failureReasons:
    status === "pass" ? [] : [mapNarrativeCheckFailure(checkId, error)],
});

export const orderNarrativeCheckItems = (
  items: ReadonlyMap<
    NarrativeAutoCheckId,
    NarrativeAutoCheckReportInput["checks"][number]
  >,
) =>
  NARRATIVE_AUTO_CHECK_IDS.map((checkId) => {
    const item = items.get(checkId);
    if (item === undefined) {
      return createNarrativeCheckItem({
        checkId,
        status: "fail",
        error: new Error("Missing check outcome."),
      });
    }
    return item;
  });
