// Generated by composition-local-renderer-registry-v1. Do not edit.
import Renderer from "./scenes/m6-scene-proof/Renderer";
import type { SceneRendererRegistry } from "../../runtime/story-visual/types";

export const rendererRegistryFingerprint =
  "sha256:d4f73aed83b88e757cb355ee81ef7610b077c829f177dbedbf615cbb41eecaec";
export const rendererSourceGraphFingerprints = {
  "m6-scene-runtime-proof-m6-scene-proof":
    "sha256:15fbb335433643ea8e29f772f3fa116808d197b27366d3e437352059cbd950a1",
} as const;
export const rendererRegistry = {
  "m6-scene-runtime-proof-m6-scene-proof": Renderer,
} as const satisfies SceneRendererRegistry;
