import { mkdir, open, readFile, rename, rm } from "node:fs/promises";
import { dirname } from "node:path";

export type RendererRegistryMode = "write" | "check";

export const writeOrCheckRendererRegistry = async ({
  destination,
  source,
  mode,
}: {
  readonly destination: string;
  readonly source: string;
  readonly mode: RendererRegistryMode;
}): Promise<void> => {
  if (mode === "check") {
    if ((await readFile(destination, "utf8")) !== source) {
      throw new Error("RendererRegistry generated bytes are stale.");
    }
    return;
  }
  try {
    if ((await readFile(destination, "utf8")) === source) return;
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code !== "ENOENT") throw error;
  }
  await mkdir(dirname(destination), { recursive: true });
  const temporary = `${destination}.tmp-${process.pid}-${Date.now()}`;
  const handle = await open(temporary, "wx");
  try {
    await handle.writeFile(source, "utf8");
    await handle.sync();
  } finally {
    await handle.close();
  }
  try {
    await rename(temporary, destination);
  } finally {
    await rm(temporary, { force: true });
  }
};
