// Generated by project-registry-generator-v1. Do not edit.
import type { ComponentType } from "react";

import type { StoryCompositionProps } from "@axmorf/studio/contracts";

export type ProjectRegistryEntry = {
  readonly id: string;
  readonly fps: number;
  readonly width: number;
  readonly height: number;
  readonly durationInFrames: number;
  readonly defaultProps: StoryCompositionProps;
  readonly generatedEntryChecksum: string;
  readonly projectRegistryEntryFingerprint: string;
  readonly narrativeBaselineFingerprint: string;
  readonly load: () => Promise<{
    default: ComponentType<StoryCompositionProps>;
  }>;
};

export const projectRegistryGeneratorId =
  "project-registry-generator-v1" as const;

export const projectRegistry =
  [] as const satisfies readonly ProjectRegistryEntry[];
