import { format } from "prettier";

import {
  computeGeneratedRegistryEntryChecksum,
  computeNarrativeBaselineFingerprint,
  computeProjectRegistryEntryFingerprint,
  NARRATIVE_CORE_VERSION,
  PROJECT_REGISTRY_GENERATOR_ID,
  type M1ArtifactBundle,
  type ProjectRegistrationDescriptor,
  type Sha256Digest,
} from "../../src/contracts";

export type ValidatedProjectRegistrationEntry = {
  readonly descriptor: ProjectRegistrationDescriptor;
  readonly generatedEntryChecksum: Sha256Digest;
  readonly projectRegistryEntryFingerprint: Sha256Digest;
  readonly narrativeBaselineFingerprint: Sha256Digest;
};

export const createValidatedProjectRegistrationEntry = ({
  descriptor,
  artifactBundle,
}: {
  readonly descriptor: ProjectRegistrationDescriptor;
  readonly artifactBundle: M1ArtifactBundle;
}): ValidatedProjectRegistrationEntry => {
  const generatedEntryChecksum =
    computeGeneratedRegistryEntryChecksum(descriptor);
  const projectRegistryEntryFingerprint =
    computeProjectRegistryEntryFingerprint({
      descriptor,
      semanticTimingFingerprint: artifactBundle.semanticTiming.fingerprint,
      generatedEntryChecksum,
      generatorId: PROJECT_REGISTRY_GENERATOR_ID,
    });
  const narrativeBaselineFingerprint = computeNarrativeBaselineFingerprint({
    artifactBundle,
    projectRegistryEntryFingerprint,
    narrativeCoreVersion: NARRATIVE_CORE_VERSION,
  });
  return {
    descriptor,
    generatedEntryChecksum,
    projectRegistryEntryFingerprint,
    narrativeBaselineFingerprint,
  };
};

const renderEntry = (entry: ValidatedProjectRegistrationEntry): string => {
  const { descriptor } = entry;
  return `{
    id: ${JSON.stringify(descriptor.id)},
    fps: ${descriptor.fps},
    width: ${descriptor.width},
    height: ${descriptor.height},
    durationInFrames: ${descriptor.durationInFrames},
    defaultProps: ${JSON.stringify(descriptor.defaultProps)} as StoryCompositionProps,
    generatedEntryChecksum: ${JSON.stringify(entry.generatedEntryChecksum)},
    projectRegistryEntryFingerprint: ${JSON.stringify(entry.projectRegistryEntryFingerprint)},
    narrativeBaselineFingerprint: ${JSON.stringify(entry.narrativeBaselineFingerprint)},
    load: () => import(${JSON.stringify(descriptor.compositionModulePath)}),
  }`;
};

export const renderProjectRegistrySource = async (
  entries: readonly ValidatedProjectRegistrationEntry[],
): Promise<string> => {
  const sorted = [...entries].sort((left, right) =>
    left.descriptor.id.localeCompare(right.descriptor.id),
  );
  const seenIds = new Set<string>();
  for (const entry of sorted) {
    if (seenIds.has(entry.descriptor.id)) {
      throw new Error(`Duplicate Composition ID: ${entry.descriptor.id}.`);
    }
    seenIds.add(entry.descriptor.id);
  }

  const source = `// Generated by ${PROJECT_REGISTRY_GENERATOR_ID}. Do not edit.
import type { ComponentType } from "react";

import type { StoryCompositionProps } from "../contracts";

export type ProjectRegistryEntry = {
  readonly id: string;
  readonly fps: number;
  readonly width: number;
  readonly height: number;
  readonly durationInFrames: number;
  readonly defaultProps: StoryCompositionProps;
  readonly generatedEntryChecksum: string;
  readonly projectRegistryEntryFingerprint: string;
  readonly narrativeBaselineFingerprint: string;
  readonly load: () => Promise<{
    default: ComponentType<StoryCompositionProps>;
  }>;
};

export const projectRegistryGeneratorId = ${JSON.stringify(PROJECT_REGISTRY_GENERATOR_ID)} as const;

export const projectRegistry = [
${sorted.map(renderEntry).join(",\n")}
] as const satisfies readonly ProjectRegistryEntry[];
`;
  return `${(await format(source, { parser: "typescript" })).trimEnd()}\n`;
};
