import { mkdir, open, readFile, rename, unlink } from "node:fs/promises";
import { basename, dirname, join } from "node:path";
import { randomUUID } from "node:crypto";

import { StoryIdSchema } from "../../src/contracts";

import { renderProjectRegistrySource } from "./domain";
import {
  discoverProjectEntries,
  loadProjectRegistrationEntry,
} from "./project-files";

export type RegistryGenerationMode = "write" | "check";

export type ProjectRegistryGenerationResult = {
  readonly mode: RegistryGenerationMode;
  readonly entryCount: number;
  readonly destination: string;
};

const syncDirectory = async (directory: string): Promise<void> => {
  let handle;
  try {
    handle = await open(directory, "r");
    await handle.sync();
  } catch (error) {
    const code = (error as NodeJS.ErrnoException).code;
    if (code !== "EINVAL" && code !== "ENOTSUP" && code !== "EBADF") {
      throw error;
    }
  } finally {
    await handle?.close();
  }
};

const writeAtomic = async (destination: string, source: string) => {
  const parent = dirname(destination);
  await mkdir(parent, { recursive: true });
  const temporaryPath = join(
    parent,
    `.${basename(destination)}.${process.pid}.${randomUUID()}.tmp`,
  );
  let renamed = false;
  try {
    const handle = await open(temporaryPath, "wx");
    try {
      await handle.writeFile(source, "utf8");
      await handle.sync();
    } finally {
      await handle.close();
    }
    await rename(temporaryPath, destination);
    renamed = true;
    await syncDirectory(parent);
  } finally {
    if (!renamed) {
      await unlink(temporaryPath).catch((error: NodeJS.ErrnoException) => {
        if (error.code !== "ENOENT") throw error;
      });
    }
  }
};

export const generateProjectRegistry = async ({
  rootDir,
  mode,
  excludeProjectIds = [],
}: {
  readonly rootDir: string;
  readonly mode: RegistryGenerationMode;
  readonly excludeProjectIds?: readonly string[];
}): Promise<ProjectRegistryGenerationResult> => {
  const excludedCompositionPaths = new Set(
    excludeProjectIds.map(
      (projectId) =>
        `src/projects/${StoryIdSchema.parse(projectId)}/Composition.tsx`,
    ),
  );
  const compositionPaths = (await discoverProjectEntries(rootDir)).filter(
    (compositionPath) => !excludedCompositionPaths.has(compositionPath),
  );
  const entries = await Promise.all(
    compositionPaths.map((compositionPath) =>
      loadProjectRegistrationEntry({ rootDir, compositionPath }),
    ),
  );
  const expected = await renderProjectRegistrySource(entries);
  const destination = join(
    rootDir,
    "src/projects/project-registry.generated.ts",
  );
  if (mode === "check") {
    let actual: string;
    try {
      actual = await readFile(destination, "utf8");
    } catch (error) {
      if ((error as NodeJS.ErrnoException).code === "ENOENT") {
        throw new Error("ProjectRegistry drift: generated file is missing.");
      }
      throw error;
    }
    if (actual !== expected) {
      throw new Error("ProjectRegistry drift: generated bytes are stale.");
    }
  } else {
    let actual: string | undefined;
    try {
      actual = await readFile(destination, "utf8");
    } catch (error) {
      if ((error as NodeJS.ErrnoException).code !== "ENOENT") throw error;
    }
    if (actual !== expected) await writeAtomic(destination, expected);
  }
  return { mode, entryCount: entries.length, destination };
};
