import { randomUUID } from "node:crypto";
import { mkdir, open, readFile, rename, unlink } from "node:fs/promises";
import { basename, dirname, join } from "node:path";

import { buildResourceCatalog, renderResourceCatalogJson } from "./domain";
import { loadWorkspaceCatalogAuthorityDescriptors } from "./project-files";
import {
  createWorkspaceProjectStorageLocations,
  type ProjectStorageLocations,
} from "../projects/project-locations";
import type { ProductionLocations } from "../project-production/application/production-locations";

export type CatalogGenerationMode = "write" | "check";

export type CatalogGenerationResult = {
  readonly mode: CatalogGenerationMode;
  readonly entryCount: number;
  readonly destination: string;
};

export type ProjectCatalogProjectionPort = (input: {
  readonly locations: ProductionLocations;
  readonly projectId: string;
  readonly mode: CatalogGenerationMode;
}) => Promise<
  Readonly<{
    catalog: import("../../src/contracts").ResourceCatalog;
  }>
>;

const syncDirectory = async (directory: string): Promise<void> => {
  let handle;
  try {
    handle = await open(directory, "r");
    await handle.sync();
  } catch (error) {
    const code = (error as NodeJS.ErrnoException).code;
    if (code !== "EINVAL" && code !== "ENOTSUP" && code !== "EBADF") {
      throw error;
    }
  } finally {
    await handle?.close();
  }
};

const writeAtomic = async (destination: string, contents: string) => {
  const parent = dirname(destination);
  await mkdir(parent, { recursive: true });
  const temporaryPath = join(
    parent,
    `.${basename(destination)}.${process.pid}.${randomUUID()}.tmp`,
  );
  let renamed = false;
  try {
    const handle = await open(temporaryPath, "wx");
    try {
      await handle.writeFile(contents, "utf8");
      await handle.sync();
    } finally {
      await handle.close();
    }
    await rename(temporaryPath, destination);
    renamed = true;
    await syncDirectory(parent);
  } finally {
    if (!renamed) {
      await unlink(temporaryPath).catch((error: NodeJS.ErrnoException) => {
        if (error.code !== "ENOENT") throw error;
      });
    }
  }
};

const writeOrCheckCatalog = async ({
  destination,
  expected,
  mode,
  label,
}: {
  readonly destination: string;
  readonly expected: string;
  readonly mode: CatalogGenerationMode;
  readonly label: string;
}) => {
  let actual: string | undefined;
  try {
    actual = await readFile(destination, "utf8");
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code !== "ENOENT") throw error;
  }
  if (mode === "check") {
    if (actual === undefined) {
      throw new Error(`${label} drift: generated file is missing.`);
    }
    if (actual !== expected) {
      throw new Error(`${label} drift: generated bytes are stale.`);
    }
  } else if (actual !== expected) {
    await writeAtomic(destination, expected);
  }
};

export const generateResourceCatalogForStorage = async ({
  storage,
  mode,
  loadDescriptors,
}: {
  readonly storage: ProjectStorageLocations;
  readonly mode: CatalogGenerationMode;
  readonly loadDescriptors: () => Promise<
    readonly import("../../src/contracts").ResourceDescriptor[]
  >;
}): Promise<CatalogGenerationResult> => {
  const catalog = buildResourceCatalog(await loadDescriptors());
  const expected = renderResourceCatalogJson(catalog);
  const destination = storage.catalogProjectionPath;
  await writeOrCheckCatalog({
    destination,
    expected,
    mode,
    label: "ResourceCatalog",
  });
  return { mode, entryCount: catalog.entries.length, destination };
};

export const generateWorkspaceResourceCatalog = async ({
  locations,
  mode,
}: {
  readonly locations: ProductionLocations;
  readonly mode: CatalogGenerationMode;
}) =>
  generateResourceCatalogForStorage({
    storage: createWorkspaceProjectStorageLocations(locations),
    mode,
    loadDescriptors: () =>
      loadWorkspaceCatalogAuthorityDescriptors({ locations }),
  });

export const generateProjectResourceCatalogForStorage = async ({
  storage,
  projectId,
  mode,
  loadDescriptors,
}: {
  readonly storage: ProjectStorageLocations;
  readonly projectId: string;
  readonly mode: CatalogGenerationMode;
  readonly loadDescriptors: () => Promise<
    readonly import("../../src/contracts").ResourceDescriptor[]
  >;
}) => {
  const catalog = buildResourceCatalog(await loadDescriptors());
  const destination = join(
    storage.projectSourceRoot,
    projectId,
    "generated/resource-catalog.generated.json",
  );
  await writeOrCheckCatalog({
    destination,
    expected: renderResourceCatalogJson(catalog),
    mode,
    label: "Project ResourceCatalog",
  });
  return {
    mode,
    entryCount: catalog.entries.length,
    destination,
    catalog,
  } as const;
};

export const generateWorkspaceProjectResourceCatalog = async ({
  locations,
  projectId,
  mode,
}: {
  readonly locations: ProductionLocations;
  readonly projectId: string;
  readonly mode: CatalogGenerationMode;
}) =>
  generateProjectResourceCatalogForStorage({
    storage: createWorkspaceProjectStorageLocations(locations),
    projectId,
    mode,
    loadDescriptors: () =>
      loadWorkspaceCatalogAuthorityDescriptors({ locations, projectId }),
  });
