import { randomUUID } from "node:crypto";
import { mkdir, open, readFile, rename, unlink } from "node:fs/promises";
import { basename, dirname, join } from "node:path";

import { buildResourceCatalog, renderResourceCatalogJson } from "./domain";
import { loadCatalogAuthorityDescriptors } from "./project-files";

export type CatalogGenerationMode = "write" | "check";

export type CatalogGenerationResult = {
  readonly mode: CatalogGenerationMode;
  readonly entryCount: number;
  readonly destination: string;
};

const syncDirectory = async (directory: string): Promise<void> => {
  let handle;
  try {
    handle = await open(directory, "r");
    await handle.sync();
  } catch (error) {
    const code = (error as NodeJS.ErrnoException).code;
    if (code !== "EINVAL" && code !== "ENOTSUP" && code !== "EBADF") {
      throw error;
    }
  } finally {
    await handle?.close();
  }
};

const writeAtomic = async (destination: string, contents: string) => {
  const parent = dirname(destination);
  await mkdir(parent, { recursive: true });
  const temporaryPath = join(
    parent,
    `.${basename(destination)}.${process.pid}.${randomUUID()}.tmp`,
  );
  let renamed = false;
  try {
    const handle = await open(temporaryPath, "wx");
    try {
      await handle.writeFile(contents, "utf8");
      await handle.sync();
    } finally {
      await handle.close();
    }
    await rename(temporaryPath, destination);
    renamed = true;
    await syncDirectory(parent);
  } finally {
    if (!renamed) {
      await unlink(temporaryPath).catch((error: NodeJS.ErrnoException) => {
        if (error.code !== "ENOENT") throw error;
      });
    }
  }
};

const writeOrCheckCatalog = async ({
  destination,
  expected,
  mode,
  label,
}: {
  readonly destination: string;
  readonly expected: string;
  readonly mode: CatalogGenerationMode;
  readonly label: string;
}) => {
  let actual: string | undefined;
  try {
    actual = await readFile(destination, "utf8");
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code !== "ENOENT") throw error;
  }
  if (mode === "check") {
    if (actual === undefined) {
      throw new Error(`${label} drift: generated file is missing.`);
    }
    if (actual !== expected) {
      throw new Error(`${label} drift: generated bytes are stale.`);
    }
  } else if (actual !== expected) {
    await writeAtomic(destination, expected);
  }
};

export const generateResourceCatalog = async ({
  rootDir,
  mode,
  loadDescriptors = loadCatalogAuthorityDescriptors,
}: {
  readonly rootDir: string;
  readonly mode: CatalogGenerationMode;
  readonly loadDescriptors?: typeof loadCatalogAuthorityDescriptors;
}): Promise<CatalogGenerationResult> => {
  const catalog = buildResourceCatalog(await loadDescriptors(rootDir));
  const expected = renderResourceCatalogJson(catalog);
  const destination = join(
    rootDir,
    "src/remotion/catalog/resource-catalog.generated.json",
  );
  await writeOrCheckCatalog({
    destination,
    expected,
    mode,
    label: "ResourceCatalog",
  });
  return { mode, entryCount: catalog.entries.length, destination };
};

export const generateProjectResourceCatalog = async ({
  rootDir,
  projectId,
  mode,
  loadDescriptors = loadCatalogAuthorityDescriptors,
}: {
  readonly rootDir: string;
  readonly projectId: string;
  readonly mode: CatalogGenerationMode;
  readonly loadDescriptors?: typeof loadCatalogAuthorityDescriptors;
}) => {
  const catalog = buildResourceCatalog(
    await loadDescriptors(rootDir, projectId),
  );
  const destination = join(
    rootDir,
    `src/projects/${projectId}/generated/resource-catalog.generated.json`,
  );
  await writeOrCheckCatalog({
    destination,
    expected: renderResourceCatalogJson(catalog),
    mode,
    label: "Project ResourceCatalog",
  });
  return {
    mode,
    entryCount: catalog.entries.length,
    destination,
    catalog,
  } as const;
};
