// Generated by composition-local-renderer-registry-v1. Do not edit.
import Renderer from "./scenes/runtime-proof-scene/Renderer";
import type { SceneRendererRegistry } from "../../../src/remotion/runtime/story-visual/types";

export const rendererRegistryFingerprint =
  "sha256:0a1d9094d9226a5e56273899063503d52cf74ecc2aea298d1a2001d1384de540";
export const rendererSourceGraphFingerprints = {
  "scene-runtime-proof-runtime-proof-scene":
    "sha256:5690a0fa9687e8d79e38d6945c41b78a1258258fb65fcdade9efe9678adbda9a",
} as const;
export const rendererRegistry = {
  "scene-runtime-proof-runtime-proof-scene": Renderer,
} as const satisfies SceneRendererRegistry;
