// Generated by project-registry-generator-v1. Do not edit.
import type { ComponentType } from "react";

import type { StoryCompositionProps } from "../contracts";

export type ProjectRegistryEntry = {
  readonly id: string;
  readonly fps: number;
  readonly width: number;
  readonly height: number;
  readonly durationInFrames: number;
  readonly defaultProps: StoryCompositionProps;
  readonly generatedEntryChecksum: string;
  readonly projectRegistryEntryFingerprint: string;
  readonly narrativeBaselineFingerprint: string;
  readonly load: () => Promise<{
    default: ComponentType<StoryCompositionProps>;
  }>;
};

export const projectRegistryGeneratorId =
  "project-registry-generator-v1" as const;

export const projectRegistry = [
  {
    id: "GpsRelativity",
    fps: 30,
    width: 1920,
    height: 1080,
    durationInFrames: 1731,
    defaultProps: { projectId: "gps-relativity" } as StoryCompositionProps,
    generatedEntryChecksum:
      "sha256:d39a9c87446efdc2796402b4154484371c080580cd8d9d79cd82f9e5e5bc46ec",
    projectRegistryEntryFingerprint:
      "sha256:25f60e077179d5da6a13dda813a808095eb74c8e4afdfbb4e8f8bbe964ea6f59",
    narrativeBaselineFingerprint:
      "sha256:8e55b2c7d31f4b56ee777e9d806744327f90ba76f973e41146e4809fa09458c9",
    load: () => import("./gps-relativity/Composition"),
  },
] as const satisfies readonly ProjectRegistryEntry[];
