// Generated by project-registry-generator-v1. Do not edit.
import type { ComponentType } from "react";

import type { StoryCompositionProps } from "../contracts";

export type ProjectRegistryEntry = {
  readonly id: string;
  readonly fps: number;
  readonly width: number;
  readonly height: number;
  readonly durationInFrames: number;
  readonly defaultProps: StoryCompositionProps;
  readonly generatedEntryChecksum: string;
  readonly projectRegistryEntryFingerprint: string;
  readonly narrativeBaselineFingerprint: string;
  readonly load: () => Promise<{
    default: ComponentType<StoryCompositionProps>;
  }>;
};

export const projectRegistryGeneratorId =
  "project-registry-generator-v1" as const;

export const projectRegistry = [
  {
    id: "AlgorithmModelAiSystem",
    fps: 30,
    width: 1080,
    height: 1920,
    durationInFrames: 1510,
    defaultProps: {
      projectId: "algorithm-model-ai-system",
    } as StoryCompositionProps,
    generatedEntryChecksum:
      "sha256:63f03a1b8039591d6303c85b5f4484bccead2d2c4ce9dc108f17356bafd483d4",
    projectRegistryEntryFingerprint:
      "sha256:d19535eec5b9ba7a406c809b76ab3511400c223d02e219901725768cb382691d",
    narrativeBaselineFingerprint:
      "sha256:c0e2cd3ec3460bd699c9e1d8f243308b121be4d88dfb667b2e64b265bff76347",
    load: () => import("./algorithm-model-ai-system/Composition"),
  },
  {
    id: "GpsRelativity",
    fps: 30,
    width: 1920,
    height: 1080,
    durationInFrames: 1731,
    defaultProps: { projectId: "gps-relativity" } as StoryCompositionProps,
    generatedEntryChecksum:
      "sha256:d39a9c87446efdc2796402b4154484371c080580cd8d9d79cd82f9e5e5bc46ec",
    projectRegistryEntryFingerprint:
      "sha256:25f60e077179d5da6a13dda813a808095eb74c8e4afdfbb4e8f8bbe964ea6f59",
    narrativeBaselineFingerprint:
      "sha256:ee5a1af1f9dc9017cdb3fa43cb781defad184654fcd93873812122d748650244",
    load: () => import("./gps-relativity/Composition"),
  },
  {
    id: "MachineLearningBasics",
    fps: 30,
    width: 1080,
    height: 1920,
    durationInFrames: 1974,
    defaultProps: {
      projectId: "machine-learning-basics",
    } as StoryCompositionProps,
    generatedEntryChecksum:
      "sha256:505e4c19f19b1d9acc7012c8f25982d56f694f39ff45e85d262128ef3fbd609a",
    projectRegistryEntryFingerprint:
      "sha256:ac336aab2a110369e230f7c61b0bb7b6b834ce085fb2bb17b663762092561c95",
    narrativeBaselineFingerprint:
      "sha256:26ec73b76ce276e8202236aad612b3190ddbecb62f4f6acbb4a870866f56f10c",
    load: () => import("./machine-learning-basics/Composition"),
  },
  {
    id: "ProductComicVertical",
    fps: 30,
    width: 1080,
    height: 1920,
    durationInFrames: 5116,
    defaultProps: {
      projectId: "product-comic-vertical",
    } as StoryCompositionProps,
    generatedEntryChecksum:
      "sha256:523287cbd160f46fb7f93ab25e2a0d8980c09dffe3ad462cb9b67185128f0de0",
    projectRegistryEntryFingerprint:
      "sha256:ba25a8a3b1ff21cf7196550f26c64f78846a25a0ab3399f9b3571c0377605196",
    narrativeBaselineFingerprint:
      "sha256:476ef4329d80feb33b130b51ad4c643cc4693a0a7035bccd4d429b212b303b13",
    load: () => import("./product-comic-vertical/Composition"),
  },
  {
    id: "RoundedAirplaneWindows",
    fps: 30,
    width: 1080,
    height: 1920,
    durationInFrames: 1102,
    defaultProps: {
      projectId: "rounded-airplane-windows",
    } as StoryCompositionProps,
    generatedEntryChecksum:
      "sha256:2484cff421cb6e97f3462c9a605e4b376054f557c9a08280bf411795c3aeabdd",
    projectRegistryEntryFingerprint:
      "sha256:e47191f0a0b142a4f82f83a36f180f933b235ca8a852ed65943113307d59c611",
    narrativeBaselineFingerprint:
      "sha256:1a3ffb7ce3827a90312e1c0d681130a0ca755c5747c0b48e6bf3d59f597afbf0",
    load: () => import("./rounded-airplane-windows/Composition"),
  },
] as const satisfies readonly ProjectRegistryEntry[];
